## WORKING WITH OPENCV

In [1]:
import cv2

### Reading in the image

In [2]:
# parameter-> path , color(grayscale,colored etc)
img=cv2.imread('data/lena.jpg',0)
print(img)

[[163 162 161 ... 170 154 130]
 [162 162 162 ... 173 155 126]
 [162 162 163 ... 170 155 128]
 ...
 [ 43  42  51 ... 103 101  99]
 [ 41  42  55 ... 103 105 106]
 [ 42  44  57 ... 102 106 109]]


#### Waitkey helps set the time for which image would be displayed in the image window 
#### Destroy all window destroys all the opened images

In [4]:
# parameters-> window name , file name
cv2.imshow('image',img)

# time for which window will be displayed
cv2.waitKey(5000)

# closes all the opened windows
cv2.destroyAllWindows()

In [6]:
# parameters-> name of the file , file to be dispalyed in the named file
cv2.imwrite("lena_copy.png",img)

True

##### Customizing settings such as image is closed on pressing ESC and saved on predssing save button

In [7]:
k=cv2.waitKey(0)

# if key pressed is ESC close the window and if it is "s" save the window and close it
if(k==27):
    cv2.destroyAllWindows()
elif k==ord('s'):
    cv2.imwrite("lena_copy2.png",img)
    cv2.destroyAllWindows()

### WORKING WITH VIDEOS

In [3]:
# parameter of Videocapture-> 0 for default camera
cap=cv2.VideoCapture(0)

# cap.isOpened() -> is true only when all information regarding the video is correct
while(cap.isOpened()):
    
#     ret->boolean true or false that is checks whether the frame is present or not
#     frame-> frame of the video
    ret,frame=cap.read()
    
#     used to get the frame width and height res[ectively]
    width=cap.get(cv2.CAP_PROP_FRAME_WIDTH)
    height=cap.get(cv2.CAP_PROP_FRAME_HEIGHT)
    print(width , height)
    
#     parameter-> name of the window , frames
    cv2.imshow("Video",frame)
    
#     if kwy pressed is "q" then quit
    if(cv2.waitKey(1) & 0xFF == ord('q')):
        break
        
#releases the window
cap.release()

# closes all the opened window
cv2.destroyAllWindows()

640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0
640.0 480.0


#### Converting video to grayscale

In [2]:
# parameter of Videocapture-> 0 for default camera
cap=cv2.VideoCapture(0)
while(True):
    
#     ret->boolean true or false that is checks whether the frame is present or not
#     frame-> frame of the video
    ret,frame=cap.read()
    
#     converting the video into grayscale by passing colored t ogray parameter
#  Parameters-> source , colr change
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    
#     parameter-> name of the window , frames
    cv2.imshow("Video",gray)
    
#     if key pressed is "q" then quit
    if(cv2.waitKey(1) & 0xFF == ord('q')):
        break
        
#releases the window
cap.release()

# closes all the opened window
cv2.destroyAllWindows()

### DRAWING GEOMETRIC SHAPES ON IMAGES

In [2]:
img2=cv2.imread("data/lena.jpg",1)
cv2.imshow("image",img2)
cv2.waitKey(5000)
cv2.destroyAllWindows()

### Draw a line over the image

In [3]:
# parameters - >
#   source -> image over which line is to be drawn
#     pt1-> initial co-ordinate of line
#     pt2-> final co-ordinates of the line
#     color -> (B,G,R)
#     thickness - in range starting from 1
img2_with_line=cv2.line(img2 , (0 , 0) , (255,255) , (0,255,0) , 1)
cv2.imshow("image",img2_with_line)
cv2.waitKey(5000)
cv2.destroyAllWindows()

### Draw arrrowed line over the omage

In [4]:
# parameters - >
#   source -> image over which line is to be drawn
#     pt1-> initial co-ordinate of line
#     pt2-> final co-ordinates of the line
#     color -> (B,G,R)
#     thickness - in range starting from 1
img2_with_arrowedline=cv2.arrowedLine(img2 , (0 , 0) , (255,255) , (0,255,0) , 1)
cv2.imshow("image",img2_with_arrowedline)
cv2.waitKey(5000)
cv2.destroyAllWindows()

### Draw rectangle

In [6]:
# parameters - >
#   source -> image over which rectangle is to be drawn
#     pt1-> top-left co-ordinate of rectangle
#     pt2->  bottom-right co-ordinate of rectangle
#     color -> (B,G,R)
#     thickness - in range starting from 1
img2_with_rectangle=cv2.rectangle(img2 , (384 , 0) , (510,128) , (255,0,0) , 5)
cv2.imshow("image",img2_with_rectangle)
cv2.waitKey(5000)
cv2.destroyAllWindows()

#### Filling the rectangle with color

##### Provide thickness as -1

In [9]:
# parameters - >
#   source -> image over which filled rectangle is to be drawn
#     pt1-> top-left co-ordinate of rectangle
#     pt2->  bottom-right co-ordinate of rectangle
#     color -> (B,G,R)
#     thickness - in range starting from 1
img2_with_rectangle=cv2.rectangle(img2 , (384 , 0) , (510,128) , (255,0,0) , -1)
cv2.imshow("image",img2_with_rectangle)
cv2.waitKey(5000)
cv2.destroyAllWindows()

### Drawing circle

In [11]:
# parameters->
#     source - image over which circle is to be drawn
#     pt1-> co-ordinates of center if circle
#     radius of circle
#     thickness of circle
img2_with_circle=cv2.circle(img2 , (0,0) , 63 , (0,255,0) , -1)
cv2.imshow("image",img2_with_circle)
cv2.waitKey(5000)
cv2.destroyAllWindows()

### Writing text over image

In [16]:
# parameters->
#     source of image
#     text to be written
#     starting - poition of text
#     font - face
#     size of font
#     color of text
#     thickness of line
#     line type
font=cv2.FONT_HERSHEY_COMPLEX
img2_with_text=cv2.putText(img2 , "OpenCV" ,(10,500), font , 4 , (0,255,0) , 5 , cv2.LINE_AA)
cv2.imshow("image",img2_with_text)
cv2.waitKey(5000)
cv2.destroyAllWindows()

### Creating image using numpy zeroes method

In [17]:
import numpy as np
# np.zeroes([height , width , length] , datatype)
#  gives black image->
img3=np.zeros([512,512,3],np.uint8)
cv2.imshow("image",img3)
cv2.waitKey(5000)
cv2.destroyAllWindows()

## ADDING TEXT TO VIDEO

#### Adding present date and time

In [2]:
# import datetime to get present date time
import datetime

# parameter of Videocapture-> 0 for default camera
cap=cv2.VideoCapture(0)
while(True):
    
#     ret->boolean true or false that is checks whether the frame is present or not
#     frame-> frame of the video
    ret,frame=cap.read()
    
#     converting the video into grayscale by passing colored t ogray parameter
#  Parameters-> source , colr change
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    
#     PARAMETERS
#     source
#     text
#     initial co-ordinate of the text
#     font family
#     font - scale
#     color
#     thickness
#     line type
    font=cv2.FONT_HERSHEY_COMPLEX
    present_datetime=str(datetime.datetime.now())
    gray=cv2.putText(gray , present_datetime , (10,50) , font , 1 , (0,255,255) , 2 , cv2.LINE_AA)
    
    
#     parameter-> name of the window , frames
    cv2.imshow("Video",gray)
    
#     if kwy pressed is "q" then quit
    if(cv2.waitKey(1) & 0xFF == ord('q')):
        break
        
#releases the window
cap.release()

# closes all the opened window
cv2.destroyAllWindows()

## HANDLING MOUSE EVENTS IN CV2

#### seeing all the events present in cv2 directory

In [8]:
events= [i for i in dir(cv2) if "EVENT" in i]
print(events)

['EVENT_FLAG_ALTKEY', 'EVENT_FLAG_CTRLKEY', 'EVENT_FLAG_LBUTTON', 'EVENT_FLAG_MBUTTON', 'EVENT_FLAG_RBUTTON', 'EVENT_FLAG_SHIFTKEY', 'EVENT_LBUTTONDBLCLK', 'EVENT_LBUTTONDOWN', 'EVENT_LBUTTONUP', 'EVENT_MBUTTONDBLCLK', 'EVENT_MBUTTONDOWN', 'EVENT_MBUTTONUP', 'EVENT_MOUSEHWHEEL', 'EVENT_MOUSEMOVE', 'EVENT_MOUSEWHEEL', 'EVENT_RBUTTONDBLCLK', 'EVENT_RBUTTONDOWN', 'EVENT_RBUTTONUP']


In [19]:
imgg=cv2.imread("data/baboon.jpg" , 1)
cv2.imshow("image" , imgg)

def click_event(event , x , y , flags , param):
    if(event == cv2.EVENT_LBUTTONDOWN):
#         shows the co-ordinate of the point clicked
        cordinates="coordinate:(" + str(x) + "," + str(y) + ")"
        print(cordinates)
        font=cv2.FONT_HERSHEY_COMPLEX
        textt=str(x) + " , " + str(y)
        cv2.putText(imgg , textt , (x,y) , font , 0.5 , (0,255,255) , 2 , cv2.LINE_AA)
        cv2.imshow("image" , imgg)
    if(event == cv2.EVENT_RBUTTONDOWN):
#         shows the color of the location clicked
        blue = imgg[y , x , 0]
        green = imgg[y , x , 1]
        red = imgg[y , x , 2]
        colourr="color:" + "("+"R"+str(red) + "," + "B"+str(blue)+ "," + "G"+str(green)+")"
        print(colourr)
        font=cv2.FONT_HERSHEY_COMPLEX
        textt=str(blue) + "," + str(green)+","+str(red)
        cv2.putText(imgg , textt , (x,y) , font , 0.5 , (255,0,0) , 2 , cv2.LINE_AA)
        cv2.imshow("image" , imgg)
# parameters:
# window name
# function name in clicking the image
cv2.setMouseCallback("image" , click_event)

cv2.waitKey(10000)
cv2.destroyAllWindows()

coordinate:(230,271)
color:(R234,B89,G88)
coordinate:(227,120)
color:(R134,B220,G191)
coordinate:(231,39)
color:(R145,B115,G139)
coordinate:(112,238)
color:(R231,B62,G82)
coordinate:(401,281)
color:(R160,B163,G137)
coordinate:(69,370)
color:(R47,B33,G62)
coordinate:(64,116)
color:(R99,B51,G84)
coordinate:(221,442)
coordinate:(400,130)
coordinate:(389,248)


### DRAWING LINES OVER IMAGE

In [ ]:
import numpy as np 

imgg=cv2.imread("data/baboon.jpg" , 1)
cv2.imshow("image" , imgg)
points=[]

def click_event(event , x ,y ,flags , param):
    if(event == cv2.EVENT_LBUTTONDOWN):
        points.append((x,y))
        cv2.circle(imgg , (x,y) , 5 , (0,0,255) , -1)
        if(len(points) >=2 ):
            cv2.line(imgg , points[-1] , points[-2] , (255,0,0) ,4)
        cv2.imshow("image" , imgg)
    if(event == cv2.EVENT_RBUTTONDOWN):
#         shows the color of the location clicked in another window
        blue = imgg[y , x , 0]
        green = imgg[y , x , 1]
        red = imgg[y , x , 2]
        
        my_color_image = np.zeros((512,512,3) , np.uint8)
        my_color_image[:] = [blue , green , red]
        cv2.imshow("color" , my_color_image)
        cv2.waitKey(5000)
        cv2.destroyAllWindows()
        
cv2.setMouseCallback("image" , click_event)

cv2.waitKey(10000)
cv2.destroyAllWindows()