# CREATING ARRAYS

In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3]);
arr

array([1, 2, 3])

In [4]:
type(arr)

numpy.ndarray

## N-DIMENSIONAL ARRAYS

### 0-DIMENSIONAL

In [5]:
arr=np.array(42)
arr

array(42)

### 1-DIMENSIONAL

In [6]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

### 2-DIMENSIONAL

In [7]:
arr =np.array([[1,2,3,4],[3,4,5,6]])
arr

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

### 3-DIMENSIONAL

In [8]:
arr=np.array([[[1,2,3,4],[3,4,5,6]] , [[2,2,2,4],[3,4,5,4]] ])
arr

array([[[1, 2, 3, 4],
        [3, 4, 5, 6]],

       [[2, 2, 2, 4],
        [3, 4, 5, 4]]])

### HIGHER-DIMENSIONAL

In [9]:
arr = np.array([1, 2, 3, 4],ndmin=5)
print(arr)

[[[[[1 2 3 4]]]]]


## CHECKING DIMENSIONS-

In [10]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
arr.ndim

3

## ACCESSING ARRAY ELEMENTS

In [11]:
arr =np.array([1,2,3,4])
arr[0]

1

In [12]:
arr[2]+arr[3]

7

In [13]:
arr=np.array([1,2,3,4] ,ndmin=2)
arr[0,2]

3

# SLICING

### start : end : steps...[ )

In [14]:
arr = np.array([1,2,3,4,5,6])
arr[2:4]

array([3, 4])

In [15]:
arr[0:5:2]

array([1, 3, 5])

## SLICING 2-DIMENSIONAL ARRAY

In [16]:
arr =np.array([[1,2,3,4],[3,4,5,6]])
arr

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [17]:
arr[0,0:1]

array([1])

In [18]:
arr[0:2,1:3]

array([[2, 3],
       [4, 5]])

## CHECKING DATATYPES-

In [19]:
arr =np.array([[1,2,3,4],[3,4,5,6]])
arr.dtype

dtype('int64')

In [20]:
arr=np.array(["red","blue"])
arr

array(['red', 'blue'], dtype='<U4')

In [21]:
arr.dtype

dtype('<U4')

In [22]:
arr=np.array(["red","blue rose"])
arr.dtype

dtype('<U9')

#### ASSIGNING DATATYPE WHILE CREATING ARRAY

In [23]:
arr=np.array([1,2,3],dtype=object)
arr

array([1, 2, 3], dtype=object)

### CONVERTING DATATYPES

In [24]:
arr = np.array([1.1,2,3.0,4,5,6])
arr

array([1.1, 2. , 3. , 4. , 5. , 6. ])

In [25]:
arr.dtype

dtype('float64')

In [26]:
arr=arr.astype(int)

In [27]:
arr

array([1, 2, 3, 4, 5, 6])

In [28]:
arr.dtype

dtype('int64')

## COPY VS VIEW

In [29]:
arr=np.array([1,2,3])
arrc=arr.copy()
arrv=arr.view()

In [30]:
arrc

array([1, 2, 3])

In [31]:
arrc[0]=4
arrc

array([4, 2, 3])

In [32]:
arr

array([1, 2, 3])

In [33]:
arrv

array([1, 2, 3])

In [34]:
arrv[0]=4
arrv

array([4, 2, 3])

In [35]:
arr

array([4, 2, 3])

## base function determines whether an array owns data or note

In [36]:
print(arrc.base)

None


In [37]:
print(arrv.base)

[4 2 3]


## SHAPE

In [38]:
arr =np.array([[1,2,3,4],[3,4,5,6]])
arr.shape

(2, 4)

## RESHAPING

In [39]:
arr =np.array([[1,2,3,4],[3,4,5,6]])
arr=arr.reshape(8)
arr

array([1, 2, 3, 4, 3, 4, 5, 6])

In [40]:
arr=np.array([1,234,4345,4546])
arr=arr.reshape(2,2)
arr

array([[   1,  234],
       [4345, 4546]])

In [41]:
arr=np.array([1,234,4345,4546,0,0,5,6])
arr=arr.reshape(2,2,2)
arr

array([[[   1,  234],
        [4345, 4546]],

       [[   0,    0],
        [   5,    6]]])

### RESHAPE RETURNS COPY OR VIEW??

In [42]:
print(arr.reshape(8).base)

[   1  234 4345 4546    0    0    5    6]


## ITERATING THROUGH ARRAYS

In [43]:
arr =np.array([[1,2,3,4],[3,4,5,6]])
for x in arr:
    for y in x:
        print(y)
    print()

1
2
3
4

3
4
5
6



### ITERATING THROUGH SINGLE ELEMENTS USING nditer()

In [44]:
arr =np.array([[1,2,3,4],[3,4,5,6]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
3
4
5
6


### CHANGING DATATYPES WHILE ITERATING

In [45]:
arr =np.array([[1,2,3,4],[3,4,5,6]])
for x in np.nditer(arr,flags=["buffered"],op_dtypes=["S"]):
    print(x  , x.dtype)

b'1' |S21
b'2' |S21
b'3' |S21
b'4' |S21
b'3' |S21
b'4' |S21
b'5' |S21
b'6' |S21


### ITERATING WITH DIFFERENT STEP SIZE


In [46]:
arr =np.array([[1,2,3,4],[3,4,5,6]])
for x in np.nditer(arr[:,::2]):
    print(x)

1
3
3
5


## Enumerated Iteration Using ndenumerate()

In [47]:
arr =np.array([[1,2,3,4],[3,4,5,6]])
for ID,x in np.ndenumerate(arr):
    print(ID,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 3
(1, 1) 4
(1, 2) 5
(1, 3) 6


## JOINING NUMPY ARRAYS

### USING CONCATENATE

In [52]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr=np.concatenate((arr1,arr2))
arr

array([1, 2, 3, 4, 5, 6])

### USING STACK

In [53]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr=np.stack((arr1,arr2))
arr

array([[1, 2, 3],
       [4, 5, 6]])

### STACKING ALONG ROWS

In [54]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr=np.hstack((arr1,arr2))
arr

array([1, 2, 3, 4, 5, 6])

### STACKING ALONG COLUMNS

In [56]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr=np.vstack((arr1,arr2))
arr

array([[1, 2, 3],
       [4, 5, 6]])

### STACKING ALONG HEIGHTS

In [57]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr=np.dstack((arr1,arr2))
arr

array([[[1, 4],
        [2, 5],
        [3, 6]]])

## SPLITTING ARRAYS

In [58]:
arr1=np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [60]:
arr=np.array_split(arr1,3)
arr

[array([1, 2]), array([3]), array([4])]

In [61]:
arr[0]

array([1, 2])

In [67]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 9)
newarr

[array([[1, 2, 3]]),
 array([[4, 5, 6]]),
 array([[7, 8, 9]]),
 array([[10, 11, 12]]),
 array([[13, 14, 15]]),
 array([[16, 17, 18]]),
 array([], shape=(0, 3), dtype=int64),
 array([], shape=(0, 3), dtype=int64),
 array([], shape=(0, 3), dtype=int64)]

In [68]:
newarr[1]

array([[4, 5, 6]])

## SEARCHING

### USING WHERE IS

#### RETURNS INDICES WHOSE ELEMENTS SATISFIES THE CONDITION

In [78]:
arr1=np.array([1,2,3,1,1,4])
x=np.where(arr1==1)
print(x)

(array([0, 3, 4]),)


In [79]:
even=np.where(arr1%2==0)
print(even)

(array([1, 5]),)


In [77]:
odd=np.where(arr1%2!=0)
print(odd)

(array([0, 2, 3, 4]),)


### SEARCH - SORTED

#### RETURNS INDICES WHERE THE ELEMENT TO BE INSERTED TO MANTAIN YHE ORDER OF ARRAY

In [85]:
arr = np.array([1, 7, 7, 9])
x = np.searchsorted(arr, 7)

print(x)

1


In [86]:
x=np.searchsorted(arr,7,side="right")
print(x)

3


## SORTING ARRAY

In [87]:
arr = np.array([1, 7, 9, 9,3,32,1,24,4])
np.sort(arr)
print(arr)

[ 1  7  9  9  3 32  1 24  4]


In [88]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
np.sort(arr)
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


## FILTERING ARRAY

In [93]:
arr = np.array([41, 42, 43, 44])
arr

array([41, 42, 43, 44])

In [96]:
boolean=[True,False,False,True]
arr1=arr[boolean]
print(arr1)

[41 44]


In [97]:
filter = (arr>=42)
x=arr[filter]
print(x)

[42 43 44]


## GENERATING RANDOM NUMBER

### GENERATE RANDOM NUMBER BETWEEN 0 TO 100

In [99]:
x=np.random.randint(100)
x

38

### GENERATE RANDOM FLOAT NUMBER

In [105]:
x=np.random.rand()
print(x)

0.673790127965961


### GENERATING A RANDOM ARRAY

In [106]:
arr=np.random.randint(100,size=3)
arr

array([72, 13, 72])

### 1-D ARRAY CONTAINING RANDOM ELEMENTS

In [107]:
arr=np.random.rand(5)
arr

array([0.76855283, 0.06899195, 0.99463855, 0.42157262, 0.49132157])

### RANDOM 2D ARAY WITH 3 ROW AND 5 COLUMN

In [108]:
arr=np.random.rand(3,5)
arr

array([[0.58153932, 0.88170624, 0.63944147, 0.99801083, 0.67903873],
       [0.34598952, 0.94538418, 0.21892589, 0.67868175, 0.11107488],
       [0.61643473, 0.4921006 , 0.31586866, 0.7700734 , 0.80469294]])

### GENERATING RANDOM NUMBER FROM GIVEN CHOICES

In [121]:
x=random.choice([1,2,4,6])
print(x)

4


In [123]:
x=random.choice([1,2,4,6],size=3)
x

array([2, 4, 2])

In [125]:
x=random.choice([1,2,4,6],size=(2,4))
x

array([[6, 4, 4, 6],
       [2, 2, 2, 6]])

## UFUNCS

### zip function

In [127]:
arr1 =np.array([1,4,5,7,8])
arr2=np.array([3,4,7,8,9])
arr=[]
for i,j in zip(arr1,arr2):
    arr.append(i+j)
arr

[4, 8, 12, 15, 17]

### or

In [141]:
arr = np.add(arr1,arr2)
arr

array([ 4,  8, 12, 15, 17])

In [142]:
type(np.add)

numpy.ufunc

### OUR OWN FUNCTION

In [143]:
def myfunc(x,y):
    return x+y
#ADDING MYFUNC TO NUMPY FUNCTIONS .. (function name , number of array as input , number of array as output)
myfunc = np.frompyfunc(myfunc,2,1)
arr=myfunc(arr1,arr2)
arr

array([4, 8, 12, 15, 17], dtype=object)

In [145]:
arr1 =np.array([1,4,5,7,8])
arr2=np.array([3,4,7,8,9])
arr=[]
arr=np.divmod(arr1,arr2)
arr

(array([0, 1, 0, 0, 0]), array([1, 0, 5, 7, 8]))

In [149]:
arr=np.array([-1,3,-78,-0])
arr=np.absolute(arr)
arr

array([ 1,  3, 78,  0])